server:
  port: 80
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/redis
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
redis:
  host: localhost
  port: 6379
  timeout: 10000ms
  lettuce:
    pool:
      max-active: 8      # Maksimum aktif bağlantı sayısı
      max-idle: 8        # Havuzda tutulacak maksimum boşta bağlantı
      min-idle: 0        # Havuzda minimum tutulacak boşta bağlantı
      max-wait: -1ms     # Bağlantı almak için maksimum bekleme süres


management:
endpoints:
  web:
    exposure:
      include: health,info  # Dışarıya açılacak endpoint'ler
endpoint:
  health:
    show-details: always   # Detaylı sağlık bilgisi gösterimi
    probes:
      enabled: true        # Kubernetes liveness/readiness probe desteği
health:
  redis:
    enabled: true         # Redis health check'i aktif
  db:
    enabled: true

zipkin:
  enabled: true
  base-url: http://localhost:9411
  service:
    name: benimredisim